### ISSUE TITLE
TypeError: Cannot read property 'route' of undefined

### ISSUE THREAD

**Issue by gdespres** [pgroot/express-swaggerize-ui#3]
Hello,

Since the last version 1.0.3, I have the following trace : 

TypeError: Cannot read property 'route' of undefined 
at /home/nodejs/api-criteres-1/webapp/node_modules/express-swaggerize-ui/index.js:16:57 
at Layer.handle [as handle_request] (/home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/layer.js:95:5) 
at next (/home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/route.js:131:13) 
at Route.dispatch (/home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/route.js:112:3) 
at Layer.handle [as handle_request] (/home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/layer.js:95:5) 
at /home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/index.js:277:22 at Function.process_params (/home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/index.js:330:12) 
at next (/home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/index.js:271:10) 
at Function.handle (/home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/index.js:176:3) 
at router (/home/nodejs/api-criteres-1/webapp/node_modules/express/lib/router/index.js:46:12)

when I use : 

app.use('/api-docs', swaggerUi());

The workaround is to use instead : 

app.use('/api-docs', swaggerUi({}));

You have to test if options parameter is undefined before use options.route or options.docs

@see Merge Request #4

**Comment by gdespres** [comment]
#4
